services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8090:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ../keycloak-theme/dist_keycloak:/opt/keycloak/providers
    command:
      - start-dev
      - --http-port=8080

volumes:
  keycloak_data:
